# Site Settings
title: Distilled Magazine
permalink: /:title/
paginate_path: /page:num
timezone: null

# Content Settings
markdown: kramdown
markdown_ext: "md,txt"
encoding: "utf-8"
collections:
    authors:
        output: true
        permalink: /:title/
defaults:
    -
        scope:
            path: "magazine"
        values:
            layout: "magazine"
